version: 2

builds:
  - main: ./cmd/pta2svg
    binary: pta2svg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']

changelog:
  sort: asc
